# REMEMBER TO DO THIS: git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
# then ctrl-b + I to install plugins

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'catppuccin/tmux#v2.1.3'
set -g @plugin 'tmux-plugins/tpm'

set -g @continuum-restore 'on'
set -g @resurrect-capture-pane-contents 'on'
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D 
bind k select-pane -U
bind l select-pane -R

bind -r C-h resize-pane -L;
bind -r C-j resize-pane -D;
bind -r C-k resize-pane -U;
bind -r C-l resize-pane -R;

setw -g mode-keys vi

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# new windows and panes start in the same directory as the current pane
bind c new-window -c "#{pane_current_path}";

# fix escape delay in vim
set -sg escape-time 0

set -g status-left-length 40

bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded tmux config"

run '~/.tmux/plugins/tpm/tpm'
